### PR TITLE
Emoji list update

### PR DESCRIPTION
**Pull request by acauquil**
# Emoji list update

Hi,

First of all, thank you for this awesome extension.

## WHY

I really missed having some newer emojis tho (🫠 and 🫥 which I use on a daily basis ).

## WHAT

I updated `emoji_list.py` with the up-to-date list from OpenMoji.

## HOW

- Removed some unused properties to lighten the file.

- Added `people-body` category

- Removed out-of-date `events` category.

## EXTRA NOTES

- Some OpenMoji entries have `order` set to an empty string, I simply defined an order of 9999 in that case.

- To be cleaner, I would delete all the extra entries that are not present in Noto (the [extras-openmoji category](https://openmoji.org/library/#group=extras-openmoji) for example).

Cheers !

### CODE REVIEW

**Comment by mijorus** [comment]
Hi @acauquil ,
thanks for the PR.

I'll take a look at 🫠 and 🫥 later today, but I can't accept this PR as-is, let me explain why.

My code here is dirty, because I have little to no inexperience with GTK but:

The file `emoji_list.py` should not be modified manually, instead it is generated by `precompile/emoji_list/generate_emoji_dict.py`; I use openmoji.json as the source, but I noticed that parsing the JSON at sturtup is significantly slower than loading a py dictionary, so I just decided to pre-compile it before hand.

Every modification should be in `emoji_list.py`, so we could update `openmoji.json` to the latest version.

**Comment by acauquil** [comment]
Hi,

I hadn't noticed the compile-time generation of `emoji_list.py`, I had to make a little script to generate a valid python dict from `openmoji.json` an honestly, it felt quite wrong. Really happy to hear that !

Would you rather I do it or leave it to you?

**Comment by mijorus** [comment]
The reason why the two emojis are not present is that with the older gnome runtime they were not rendered properly.

I still haven't figured it out how this runtime->font-rendering thing works, but anyway, it is time for a refresh then!

**Comment by mijorus** [comment]
New emojis coming:

https://github.com/mijorus/smile/tree/emoji-refresh-11-22

**Comment by mijorus** [comment]
https://github.com/flathub/it.mijorus.smile/pull/2#event-7727427877

**Pull request closed without merging**
