### PR TITLE
New app icon

### PR DESCRIPTION
**Pull request by reptofrog**
Preview

---

Before | After
--- | ---
image|image

### CODE REVIEW

**Comment by mijorus** [comment]
Well, it looks actually more professional, but I put all my efforts into creating the old icon 😅, and I think it doesn't look that bad after all.

Is it that ugly for you?

**Comment by reptofrog** [comment]
I actually only wanted to fix the differently sized pupils in the original icon, (if you'll look closely, you'd see that they are slightly different) but when I noticed that the original icon does not use the colors that are provided in the GNOME HIG, so I decided to play around and create a more "standardized" icon (loosely) based on the official guidelines.

If you'd like, I can open another pull request that only fixes the pupils.

**Comment by mijorus** [comment]
Well, it it wasn't clear that I don't really know how to use Inkspace.

Btw, this project has grown so yes, you might be right, it's about time the to replace the icon with a proper one.

One thing I would change from the icon you proposed is the expression on face, as it looks more "surprised" than "smiling"

**Comment by mijorus** [comment]
I would probably make the mouth just a little bit wider

**Comment by mijorus** [comment]
it mijorus smile

like this, what do you think?

**Comment by mijorus** [comment]
it mijorus smile

**Comment by mijorus** [comment]
it mijorus smile

**Comment by mijorus** [comment]
seriously, what do you think about the last one?

**Comment by mijorus** [comment]
it mijorus smile

**Comment by mijorus** [comment]
Thank you!

How do you want to show up in the Credits?

**Comment by reptofrog** [comment]
I'd like to show up as "Roman Morozov" 🙂

Don't merge just yet though, I'll try later to stretch the mouth in a way that doesn't distort the outline. (I'll match it with your latest variant as close as possible)

**Comment by mijorus** [comment]
I tried experimenting with it a little more, that's the result
it mijorus smile

**Comment by mijorus** [comment]
> I'd like to show up as "Roman Morozov" 🙂
>

**Comment by mijorus** [comment]
sorry, wrong shortcut. I'll wait your final draft then

**Comment by reptofrog** [comment]
I have updated the icon: [94447fb](https://github.com/mijorus/smile/pull/33/commits/94447fb16e2d799eda2196b00288bc3d32ea61f2)

**Comment by mijorus** [comment]
This looks perfect, thank you

**Comment by mijorus** [comment]
The next update will include the new app icon an your credit.

**Pull request merged**
